### ISSUE TITLE
What is the reason behind the ID field being a composition of partition key and a Guid?

### ISSUE THREAD

**Issue by paulvanbladel** [Azure-Samples/PartitionedRepository#5]
I Noticed that the ID field is a composition of the partition key and a Guid.
I would think the Guid with be sufficient?
Just trying to understand. 
Thanks in advance
paul.

**Comment by jomalsan** [comment]
Hi Paul,

Adding the partition key in GenerateId is paired with ResolvePartitionKey below it in the TodoItemRepository. 

```
public override string GenerateId(TodoItem entity) => $"{entity.Category}:{Guid.NewGuid()}";
public override PartitionKey ResolvePartitionKey(string entityId) => new PartitionKey(entityId.Split(':')[0]);
```

This way, when the Id is passed back in the GET endpoint, ResolvePartitionKey is used to do the query in CosmosDb as in [Line 30 of CosmosDbRepository](https://github.com/Azure-Samples/PartitionedRepository/blob/a0146f6b28b75571cbe3448a29af28efed26a527/TodoService.Infrastructure/Data/CosmosDbRepository.cs#L30)
